# Generated by Django 4.2.5 on 2023-09-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_empresa",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
