# Generated by Django 4.2.5 on 2023-09-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caixas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
