# Generated by Django 4.2.5 on 2023-09-11 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("caixas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixa",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caixas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
