# Generated by Django 4.2.5 on 2023-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caixas", "0002_alter_caixa_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=8, null=True
            ),
        ),
    ]
